# Generated by Django 3.1.3 on 2020-11-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20201120_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateprofile',
            name='code',
            field=models.IntegerField(blank=True, default=550772, null=True),
        ),
    ]
