# Generated by Django 3.1.3 on 2020-11-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_loglogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglogin',
            name='useri',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
