# Generated by Django 3.1.3 on 2020-11-20 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=150, null=True)),
                ('aciqlama', models.TextField(max_length=150, null=True)),
                ('yaranma_tarix', models.DateTimeField(auto_now_add=True)),
                ('bitme_tarixi', models.DateTimeField(null=True)),
                ('useri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
