# Generated by Django 3.1.3 on 2020-11-23 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_todopaylas'),
    ]

    operations = [
        migrations.CreateModel(
            name='serh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.CharField(max_length=350, null=True)),
                ('tarix', models.DateTimeField(auto_now_add=True)),
                ('todom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.todo')),
                ('useri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
